force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Full Name (Last Name, First Name)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Subordinates</relationshipLabel>
    <relationshipName>Subordinates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Vacation_Approval_Process_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Approval_Process_API_Name__c</fullName>
    <label>Vacation Approval Process API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TimeEntryApproveHelper.cls
public class TimeEntryApproveHelper
{
    public enum ApproveAction {Approve, Reject, Removed}
    
    private final List<TimeEntry__c> timeEntriesToApprove;

    public TimeEntryApproveHelper(List<TimeEntry__c> timeEntriesToApprove)
    {
        this.timeEntriesToApprove = timeEntriesToApprove;
    }

    public void sendForApproval()
    {
        List<Approval.ProcessSubmitRequest> requests = new List<Approval.ProcessSubmitRequest>();
        List<TimeEntry__c> timeEntries = [SELECT Location__r.Vacation_Approval_Process_API_Name__c, Employee__r.Manager__r.User__c FROM TimeEntry__c WHERE Id IN :timeEntriesToApprove];
        for (TimeEntry__c timeEntry : timeEntries)
        {
            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setProcessDefinitionNameOrId(timeEntry.Location__r.Vacation_Approval_Process_API_Name__c);
            req.setComments('Submitting request for approval.');
            req.setObjectId(timeEntry.Id);
            List<Id> approverIds = timeEntry.Employee__r.Manager__r?.User__c != null ? new List<Id>{timeEntry.Employee__r.Manager__r.User__c} : new List<Id>{UserInfo.getUserId()};
            req.setNextApproverIds(approverIds);

            requests.add(req);
        }
        List<Approval.ProcessResult> results = Approval.process(requests, false);

        List<Approval.ProcessWorkitemRequest> selfApprovedRequests = new List<Approval.ProcessWorkitemRequest>();
        for (Integer i = 0, n = results.size(); i < n; i++)
        {
            if (results.get(i).isSuccess() && timeEntries.get(i).Employee__r.Manager__r?.User__c == null)
            {
                Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
                req.setComments('Approving request.');
                req.setAction('Approve');
                req.setNextApproverIds(new List<Id>{UserInfo.getUserId()});
                req.setWorkitemId(results.get(i).getNewWorkitemIds().get(0));

                selfApprovedRequests.add(req);
            }
        }

        Approval.process(selfApprovedRequests, false);
    }

}