force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Full Name (Last Name, First Name)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Target_Working_Days__c.field-meta.xml
<CustomField>
    <fullName>Target_Working_Days__c</fullName>
    <label>Target Working Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sun</fullName>
            </value>
            <value>
                <fullName>Mon</fullName>
            </value>
            <value>
                <fullName>Tue</fullName>
            </value>
            <value>
                <fullName>Wed</fullName>
            </value>
            <value>
                <fullName>Thu</fullName>
            </value>
            <value>
                <fullName>Fri</fullName>
            </value>
            <value>
                <fullName>Sat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Hours per Day</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Work Hours</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Paid Vacation</fullName>
            </value>
            <value>
                <fullName>Sickness / Accident</fullName>
            </value>
            <value>
                <fullName>Parental Leave</fullName>
            </value>
            <value>
                <fullName>Unpaid Leave</fullName>
            </value>
            <value>
                <fullName>Approved paid absence</fullName>
            </value>
            <value>
                <fullName>Paid Education</fullName>
            </value>
            <value>
                <fullName>Child Sickness / Accident</fullName>
            </value>
            <value>
                <fullName>Absence</fullName>
                <isActive>false</isActive>
                <label>Absence</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Vacation</fullName>
                <isActive>false</isActive>
                <label>Vacation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UtilizationController.cls
public class UtilizationController
{
    private static final String WORK_TYPE = 'Work Hours';
    private static final String HOLIDAY_TYPE = 'Holiday';

//    @AuraEnabled(Cacheable=true)
//    public static Decimal getUtilization(Id employeeId, Date startDate, Date endDate)
//    {
//        Location__c location = [SELECT TargetWorkingHoursPerDay__c, Target_Working_Days__c FROM Location__c WHERE Id IN (SELECT Location__c FROM Employee__c WHERE Id = :employeeId)];
//        List<String> workingDaysNames = location.Target_Working_Days__c.split(';');
//
//        Decimal plannedWorkingHours = 0;
//        for (Date day = startDate; day <= endDate; day = day.addDays(1))
//        {
//            if (workingDaysNames.contains(((Datetime) day).format('E')))
//            {
//                plannedWorkingHours += location.TargetWorkingHoursPerDay__c;
//            }
//        }
//
//        Decimal actualWorkingHours = 0;
//        for (TimeEntry__c each : [SELECT Type__c, Hours__c FROM TimeEntry__c WHERE ((Type__c = :WORK_TYPE AND Employee__c = :employeeId) OR (Type__c = :HOLIDAY_TYPE AND Location__c = :location.Id))
//                                  AND Date__c >= :startDate AND Date__c <= :endDate])
//        {
//            if (each.Type__c == WORK_TYPE)
//            {
//                actualWorkingHours += each.Hours__c;
//            }
//            if (each.Type__c == HOLIDAY_TYPE)
//            {
//                plannedWorkingHours -= each.Hours__c;
//            }
//        }
//
//        System.debug(plannedWorkingHours);
//        System.debug(actualWorkingHours);
//        System.debug(plannedWorkingHours != 0 ? actualWorkingHours / plannedWorkingHours * 100 : 0);
//
//        return plannedWorkingHours != 0 ? actualWorkingHours / plannedWorkingHours * 100 : 0;
//
//        return null;
//    }

}