force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Full Name (Last Name, First Name)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Target_Working_Days__c.field-meta.xml
<CustomField>
    <fullName>Target_Working_Days__c</fullName>
    <label>Target Working Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sun</fullName>
            </value>
            <value>
                <fullName>Mon</fullName>
            </value>
            <value>
                <fullName>Tue</fullName>
            </value>
            <value>
                <fullName>Wed</fullName>
            </value>
            <value>
                <fullName>Thu</fullName>
            </value>
            <value>
                <fullName>Fri</fullName>
            </value>
            <value>
                <fullName>Sat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/fields/Target_Working_Hours_per_Day__c.field-meta.xml
<CustomField>
    <fullName>Target_Working_Hours_per_Day__c</fullName>
    <label>Target Working Hours per Day</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Target_Working_Hours_Per_Week__c.field-meta.xml
<CustomField>
    <fullName>Target_Working_Hours_Per_Week__c</fullName>
    <formula>(
    IF(INCLUDES(Target_Working_Days__c, &apos;Sun&apos;), 1, 0)
        + IF(INCLUDES(Target_Working_Days__c, &apos;Mon&apos;), 1, 0)
        + IF(INCLUDES(Target_Working_Days__c, &apos;Tue&apos;), 1, 0)
        + IF(INCLUDES(Target_Working_Days__c, &apos;Wed&apos;), 1, 0)
        + IF(INCLUDES(Target_Working_Days__c, &apos;Thu&apos;), 1, 0)
        + IF(INCLUDES(Target_Working_Days__c, &apos;Fri&apos;), 1, 0)
        + IF(INCLUDES(Target_Working_Days__c, &apos;Sat&apos;), 1, 0)
) * Target_Working_Hours_per_Day__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Target Working Hours per Week</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Hours per Day</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Work Hours</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Paid Vacation</fullName>
            </value>
            <value>
                <fullName>Sickness / Accident</fullName>
            </value>
            <value>
                <fullName>Parental Leave</fullName>
            </value>
            <value>
                <fullName>Unpaid Leave</fullName>
            </value>
            <value>
                <fullName>Approved paid absence</fullName>
            </value>
            <value>
                <fullName>Paid Education</fullName>
            </value>
            <value>
                <fullName>Child Sickness / Accident</fullName>
            </value>
            <value>
                <fullName>Absence</fullName>
                <isActive>false</isActive>
                <label>Absence</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Vacation</fullName>
                <isActive>false</isActive>
                <label>Vacation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FilterController.cls
public class FilterController
{
    public static final String HOLIDAY_TIME_ENTRY_TYPE = 'Holiday';

    @AuraEnabled(Cacheable=true)
    public static List<Employee__c> getEmployeesForLocations(List<Id> locationIds)
    {
        return [SELECT Name FROM Employee__c WHERE Location__c IN :locationIds];
    }

    @AuraEnabled(Cacheable=true)
    public static List<TimeEntry__c> getTimeEntries(List<Id> employeeIds, List<Id> locationIds, List<String> entryTypes, String startDate, String endDate)
    {
        Date leftEdge = Date.valueOf(startDate);
        Date rightEdge = Date.valueOf(endDate);
        String query = 'SELECT Name, Employee__r.Name, Date__c, From__c, To__c, Type__c, Hours__c, Comment__c '
                     + 'FROM TimeEntry__c WHERE To__c >= :leftEdge AND From__c <= :rightEdge';
        if (!locationIds.isEmpty())
        {
            query += ' AND Location__c IN :locationIds';
        }
        if (!employeeIds.isEmpty())
        {
            query += ' AND Employee__c IN :employeeIds';
        }
        if (!entryTypes.isEmpty())
        {
            query += ' AND Type__c IN :entryTypes';
        }
        query += ' ORDER BY Type__c';

        return Database.query(query);
    }

    @AuraEnabled(Cacheable=true)
    public static Employee__c getEmployeeInfo(Id employeeId)
    {
        return [SELECT First_Name__c, Last_Name__c, Location__r.Target_Working_Hours_per_Day__c,
                Location__r.Target_Working_Days__c, Location__r.Target_Working_Hours_Per_Week__c
                FROM Employee__c WHERE Id = :employeeId];
    }


    @AuraEnabled(Cacheable=true)
    public static Employee__c getEmployeeByEmail(String employeeEmail)
    {
        List<Employee__c> employees = [SELECT Id FROM Employee__c WHERE Email__c = :employeeEmail LIMIT 1];
        return employees.size() != 0 ? employees.get(0) : new Employee__c(Id = null);
    }

}