force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Full Name (Last Name, First Name)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Vacation_Days_Year_to_Date__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Days_Year_to_Date__c</fullName>
    <formula>FLOOR(Location__r.Vacation_Days_per_Year__c / 365 * DAYOFYEAR(TODAY()))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vacation Days Year to Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Vacation_Days_per_Year__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Days_per_Year__c</fullName>
    <label>Vacation Days per Year</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Work Hours</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Paid Vacation</fullName>
            </value>
            <value>
                <fullName>Sickness / Accident</fullName>
            </value>
            <value>
                <fullName>Parental Leave</fullName>
            </value>
            <value>
                <fullName>Unpaid Leave</fullName>
            </value>
            <value>
                <fullName>Approved paid absence</fullName>
            </value>
            <value>
                <fullName>Paid Education</fullName>
            </value>
            <value>
                <fullName>Child Sickness / Accident</fullName>
            </value>
            <value>
                <fullName>Absence</fullName>
                <isActive>false</isActive>
                <label>Absence</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Vacation</fullName>
                <isActive>false</isActive>
                <label>Vacation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmployeeVacationController.cls
public class EmployeeVacationController
{
    private static final String TIME_ENTRY_VACATION_TYPE = 'Paid Vacation';

    @AuraEnabled(Cacheable=true)
    public static Employee__c getVacationInfo(Id employeeId)
    {
        return [SELECT Location__r.Vacation_Days_per_Year__c, Vacation_Days_Year_to_Date__c, (SELECT From__c, To__c FROM TimeEntries__r
                WHERE Type__c = :TIME_ENTRY_VACATION_TYPE AND From__c = THIS_YEAR) FROM Employee__c WHERE Id = :employeeId];
    }

}